version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trip_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=localguide'
    ports:
      - '5432:5432'
