version: '3.8'

services:
  postgres:
    container_name: postgres-sql-gtb
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trip_db'
      - 'PGDATA=/var/lib/postgresql/data'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=localguide'
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - good-trip
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
#  gtb-api:
#    container_name: gtb-api
#    image: gtb/gtb:1.0.0
#    ports:
#      - 8088:8088
#    networks:
#      - good-trip
#    depends_on:
#      - postgresql
networks:
  good-trip:
    driver: bridge

volumes:
  postgres:
    driver: local
