spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/